###get all articles
GET http://localhost:3001/api/articles


### add
post http://localhost:3001/api/article
Content-Type: application/json

{
    "title":"weeew",
    "text":"first article here! ",
    "description":"one way or another",
    "author":"60f0526346d75d76e4ec61cf"
}

### comment
post http://localhost:3001/api/article/comment
Content-Type: application/json

{
   "article_id":"60fb2434ac02a2d5b4b0a0fb",
   "author_id":"60f0526346d75d76e4ec61cf",
   "comment":"comments works" 
}

### get article
get http://localhost:3001/api/article/60fb2434ac02a2d5b4b0a0fb


###Like an article 
put http://localhost:3001/api/article/like
Content-Type: application/json

{
    "id":"60fb2434ac02a2d5b4b0a0fb"
}


### commenting
put http://localhost:3001/api/article/comment
Content-Type: application/json

{
    "articleId":"60fb2434ac02a2d5b4b0a0fb",
    "authorId":"60f0526346d75d76e4ec61cf",
    "comment":"good job"
}