### getting a user 
GET http://localhost:3001/api/user/60f0526346d75d76e4ec61cf


### add
POST http://localhost:3001/api/user
Content-Type: application/json

{
    "name":"Zero",
    "email":"ZeroOne@gmail.com"
}